# Generated by Django 3.2.7 on 2021-09-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(max_length=50, unique=True)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_salary', models.IntegerField(max_length=100)),
                ('emp_age', models.IntegerField(max_length=50)),
            ],
        ),
    ]
