# Generated by Django 3.2.7 on 2021-09-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_alter_employeemodel_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_salary',
            field=models.IntegerField(),
        ),
    ]
